f = open("orcagent_solana.py", "w")
f.write("import anthropic, time, json, os, requests, base64\n")
f.write("from dotenv import load_dotenv\n")
f.write("from solders.keypair import Keypair\n")
f.write("from solders.transaction import VersionedTransaction\n")
f.write("load_dotenv()\n")
f.write("ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')\n")
f.write("WALLET_ADDRESS = os.getenv('WALLET_ADDRESS')\n")
f.write("PRIVATE_KEY = os.getenv('WALLET_PRIVATE_KEY')\n")
f.write("MAX_USDC = float(os.getenv('MAX_USDC', 50))\n")
f.write("STOP_LOSS = float(os.getenv('STOP_LOSS', 0.03))\n")
f.write("TAKE_PROFIT = float(os.getenv('TAKE_PROFIT', 0.05))\n")
f.write("INTERVAL = int(os.getenv('INTERVAL', 900))\n")
f.write("SOLANA_RPC = 'https://api.mainnet-beta.solana.com'\n")
f.write("JUPITER_BASE = 'https://quote-api.jup.ag/v6'\n")
f.write("USDC_MINT = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'\n")
f.write("TOKENS = [\n")
f.write("    {'mint': 'HMfERpVKozrefwou3dvZEegMdmyiKzeWBBDcsijDpump', 'label': 'TOKEN1'},\n")
f.write("    {'mint': 'AqQtvEvV6wTGYjxSmzzWB11K2kmWBwbdfKCNkkW3pump', 'label': 'TOKEN2'},\n")
f.write("    {'mint': '6xUoG8JtjYxKfBD3nsLGp8n9pGzKUigF5WTwWyy1pump', 'label': 'TOKEN3'},\n")
f.write("    {'mint': 'uuxWwFL6G9UjiYRZvWxJrSB18V1oKBgYrmueamREK57', 'label': 'TOKEN4'},\n")
f.write("]\n")
f.write("client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)\n")
f.write("keypair = Keypair.from_base58_string(PRIVATE_KEY)\n")
f.write("\n")
f.write("def get_token_price(mint):\n")
f.write("    try:\n")
f.write("        r = requests.get('https://api.dexscreener.com/latest/dex/tokens/' + mint, timeout=10)\n")
f.write("        r.raise_for_status()\n")
f.write("        pairs = r.json().get('pairs', [])\n")
f.write("        if pairs:\n")
f.write("            return float(pairs[0]['priceUsd'])\n")
f.write("    except: pass\n")
f.write("    return None\n")
f.write("\n")
f.write("def get_balance():\n")
f.write("    r = requests.post(SOLANA_RPC, json={'jsonrpc': '2.0', 'id': 1, 'method': 'getBalance', 'params': [WALLET_ADDRESS]}, timeout=10)\n")
f.write("    return r.json()['result']['value'] / 1e9\n")
f.write("\n")
f.write("def get_usdc_balance():\n")
f.write("    r = requests.post(SOLANA_RPC, json={'jsonrpc': '2.0', 'id': 1, 'method': 'getTokenAccountsByOwner', 'params': [WALLET_ADDRESS, {'mint': USDC_MINT}, {'encoding': 'jsonParsed'}]}, timeout=10)\n")
f.write("    accounts = r.json().get('result', {}).get('value', [])\n")
f.write("    if accounts:\n")
f.write("        return float(accounts[0]['account']['data']['parsed']['info']['tokenAmount']['uiAmount'] or 0)\n")
f.write("    return 0.0\n")
f.write("\n")
f.write("def ai_decision(label, price, sol, usdc):\n")
f.write("    prompt = 'Token:' + label + ' Price:$' + str(price) + ' SOL:' + str(round(sol,4)) + ' USDC:' + str(round(usdc,2)) + ' Solana meme coin. Reply ONLY JSON: {\"decision\":\"BUY|SELL|HOLD\",\"reasoning\":\"str\",\"confidence\":0.5,\"amount_pct\":0.3}'\n")
f.write("    msg = client.messages.create(model='claude-haiku-4-5-20251001', max_tokens=200, system='Cautious Solana meme coin trading agent. JSON only. Be very careful with meme coins.', messages=[{'role': 'user', 'content': prompt}])\n")
f.write("    raw = msg.content[0].text.strip()\n")
f.write("    if raw.startswith('```'): raw = raw.split('```')[1].lstrip('json')\n")
f.write("    return json.loads(raw.strip())\n")
f.write("\n")
f.write("def execute_swap(input_mint, output_mint, amount):\n")
f.write("    quote = requests.get(JUPITER_BASE + '/quote', params={'inputMint': input_mint, 'outputMint': output_mint, 'amount': int(amount), 'slippageBps': 100}, timeout=10).json()\n")
f.write("    swap_resp = requests.post(JUPITER_BASE + '/swap', json={'quoteResponse': quote, 'userPublicKey': WALLET_ADDRESS, 'wrapAndUnwrapSol': True}, timeout=10).json()\n")
f.write("    raw_tx = base64.b64decode(swap_resp['swapTransaction'])\n")
f.write("    tx = VersionedTransaction.from_bytes(raw_tx)\n")
f.write("    signed_tx = keypair.sign_versioned_transaction(tx)\n")
f.write("    result = requests.post(SOLANA_RPC, json={'jsonrpc': '2.0', 'id': 1, 'method': 'sendTransaction', 'params': [base64.b64encode(bytes(signed_tx)).decode(), {'encoding': 'base64'}]}, timeout=30).json()\n")
f.write("    return result.get('result', str(result))\n")
f.write("\n")
f.write("def run():\n")
f.write("    print('OrcAgent Solana MEME MULTI-TOKEN started')\n")
f.write("    print('Wallet: ' + str(WALLET_ADDRESS))\n")
f.write("    positions = {t['mint']: {'amount': 0.0, 'buy_price': 0.0} for t in TOKENS}\n")
f.write("    while True:\n")
f.write("        try:\n")
f.write("            sol = get_balance()\n")
f.write("            usdc = get_usdc_balance()\n")
f.write("            print('SOL:' + str(round(sol,4)) + ' USDC:' + str(round(usdc,2)))\n")
f.write("            for token in TOKENS:\n")
f.write("                try:\n")
f.write("                    price = get_token_price(token['mint'])\n")
f.write("                    if price is None:\n")
f.write("                        print(token['label'] + ': price not found, skipping')\n")
f.write("                        continue\n")
f.write("                    pos = positions[token['mint']]\n")
f.write("                    res = ai_decision(token['label'], price, sol, usdc)\n")
f.write("                    print(token['label'] + ' $' + str(price) + ' [' + res['decision'] + '] ' + res['reasoning'][:50])\n")
f.write("                    if res['decision'] == 'BUY' and usdc > 5:\n")
f.write("                        spend = min(usdc * res['amount_pct'], MAX_USDC / len(TOKENS))\n")
f.write("                        tx = execute_swap(USDC_MINT, token['mint'], int(spend * 1e6))\n")
f.write("                        print('BUY ' + token['label'] + ' TX: ' + str(tx))\n")
f.write("                        pos['amount'] += spend / price\n")
f.write("                        pos['buy_price'] = price\n")
f.write("                        usdc -= spend\n")
f.write("                    elif res['decision'] == 'SELL' and pos['amount'] > 0:\n")
f.write("                        tx = execute_swap(token['mint'], USDC_MINT, int(pos['amount'] * 1e6))\n")
f.write("                        print('SELL ' + token['label'] + ' TX: ' + str(tx))\n")
f.write("                        usdc += pos['amount'] * price\n")
f.write("                        pos['amount'] = pos['buy_price'] = 0.0\n")
f.write("                    if pos['amount'] > 0 and pos['buy_price'] > 0:\n")
f.write("                        chg = (price - pos['buy_price']) / pos['buy_price']\n")
f.write("                        if chg <= -STOP_LOSS or chg >= TAKE_PROFIT:\n")
f.write("                            tx = execute_swap(token['mint'], USDC_MINT, int(pos['amount'] * 1e6))\n")
f.write("                            print('SL/TP ' + token['label'] + ' ' + str(round(chg*100,1)) + '% TX: ' + str(tx))\n")
f.write("                            usdc += pos['amount'] * price\n")
f.write("                            pos['amount'] = pos['buy_price'] = 0.0\n")
f.write("                except Exception as e:\n")
f.write("                    print(token['label'] + ' error: ' + str(e))\n")
f.write("            print('Sleeping ' + str(INTERVAL) + 's...')\n")
f.write("        except Exception as e:\n")
f.write("            print('Error: ' + str(e))\n")
f.write("        time.sleep(INTERVAL)\n")
f.write("\n")
f.write("if __name__ == '__main__': run()\n")
f.close()
print("Done!")